import { StyleSheet } from "react-native";
import { Colors } from "@/constants/theme";
import { fonts } from "@/assets/fonts";

export const paymentStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: Colors.light.blackBackground,
    },
    flex1: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 40,
    },
    container: {
        flex: 1,
        //paddingHorizontal: 24,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 48,
        marginBottom: 40,
    },
    headerTitleContainer: {
        position: "absolute",
        left: 0,
        right: 0,
        alignItems: "center",
        zIndex: -1,
    },
    title: {
        color: Colors.light.white,
        fontFamily: fonts.primary.semiBold,
        fontSize: 16,
        textTransform: "uppercase",
    },
    orderDetailsTitle: {
        color: Colors.light.white,
        fontFamily: fonts.primary.medium,
        fontSize: 18,
        marginBottom: 16,
    },
    promoCodeRow: {
        marginBottom: 20,
    },
    promoCodeText: {
        color: Colors.light.green,
        fontFamily: fonts.primary.medium,
        fontSize: 14,
        textDecorationLine: "underline",
    },
    promoCodeInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: Colors.light.calendarBg,
        borderRadius: 8,
        height: 48,
        paddingHorizontal: 16,
        marginBottom: 20,
    },
    promoCodeInput: {
        flex: 1,
        color: Colors.light.white,
        fontFamily: fonts.primary.regular,
        fontSize: 14,
    },
    promoApplyBtn: {
        backgroundColor: Colors.light.grey,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 4,
    },
    promoApplyBtnActive: {
        backgroundColor: Colors.light.green,
    },
    promoApplyBtnText: {
        color: Colors.light.white,
        fontFamily: fonts.primary.bold,
        fontSize: 12,
    },
    rowItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    rowTextLight: {
        color: Colors.light.dullWhite,
        fontFamily: fonts.primary.regular,
        fontSize: 14,
    },
    rowTextBold: {
        color: Colors.light.white,
        fontFamily: fonts.primary.semiBold,
        fontSize: 14,
    },
    divider: {
        height: 1,
        backgroundColor: Colors.light.greybuttonversion,
        marginTop: 12,
        marginBottom: 16,
    },
    sectionHeaderRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    sectionTitle: {
        color: Colors.light.subtext,
        fontFamily: fonts.primary.medium,
        fontSize: 12,
    },
    scanCardContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    scanCardText: {
        color: Colors.light.green,
        fontFamily: fonts.primary.medium,
        fontSize: 12,
        marginLeft: 4,
    },
    cardInputContainer: {
        backgroundColor: Colors.light.calendarBg,
        borderRadius: 6,
        overflow: "hidden",
    },
    cardInputTop: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 12,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light.greybuttonversion,
    },
    cardInputBottom: {
        flexDirection: "row",
        alignItems: "center",
    },
    cardInput: {
        flex: 1,
        color: Colors.light.white,
        fontFamily: fonts.primary.medium,
        fontSize: 14,
        paddingVertical: 14,
    },
    cardIconsRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
    },
    cardIconBox: {
        width: 24,
        height: 16,
        backgroundColor: Colors.light.white,
        borderRadius: 2,
        alignItems: "center",
        justifyContent: "center",
    },
    cardIconText: {
        fontSize: 6,
        fontWeight: "bold",
        color: Colors.light.blackBackground,
    },
    halfInputBox: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 12,
    },
    halfInputBoxRight: {
        borderLeftWidth: 1,
        borderLeftColor: Colors.light.greybuttonversion,
    },
    inputLabel: {
        color: Colors.light.subtext,
        fontFamily: fonts.primary.medium,
        fontSize: 12,
        marginTop: 20,
        marginBottom: 8,
    },
    inputBox: {
        backgroundColor: Colors.light.calendarBg,
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 14,
        color: Colors.light.white,
        fontFamily: fonts.primary.medium,
        fontSize: 14,
    },
    dropdownBox: {
        backgroundColor: Colors.light.calendarBg,
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    dropdownLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    dropdownText: {
        color: Colors.light.white,
        fontFamily: fonts.primary.medium,
        fontSize: 14,
        marginLeft: 8,
    },
    checkboxRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 20,
        marginBottom: 40,
    },
    checkboxBox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 1.5,
        borderColor: Colors.light.icon,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    checkboxBoxSelected: {
        backgroundColor: Colors.light.green,
        borderColor: Colors.light.green,
    },
    checkboxText: {
        color: Colors.light.dullWhite,
        fontFamily: fonts.primary.regular,
        fontSize: 12,
        flex: 1,
    },
    bottomSection: {
        marginTop: "auto",
        paddingTop: 44,
    },
    termsText: {
        color: Colors.light.white,
        fontFamily: fonts.primary.regular,
        fontSize: 12,
        textAlign: "center",
        marginBottom: 16,
        lineHeight: 18,
    },
    termsTextUnderline: {
        textDecorationLine: "underline",
    },
    completeButton: {
        backgroundColor: Colors.light.inactivegreen,
    },
    completeButtonActive: {
        backgroundColor: Colors.light.green,
    },

    changeText: {
        color: Colors.light.white,
        fontFamily: fonts.primary.medium,
        fontSize: 12,
        marginRight: 4,
    },
    savedCardBox: {
        backgroundColor: Colors.light.calendarBg,
        borderRadius: 8,
        padding: 16,
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "transparent",
    },
    savedCardBoxSelected: {
        borderColor: Colors.light.green,
    },
    savedCardIconBox: {
        backgroundColor: Colors.light.white,
        borderRadius: 3,
        paddingHorizontal: 6,
        paddingVertical: 2,
        marginRight: 12,
    },
    savedCardIconText: {
        color: "#1A1F71",
        fontFamily: fonts.primary.semiBold,
        fontSize: 10,
    },
    savedCardNumber: {
        color: Colors.light.white,
        fontFamily: fonts.primary.medium,
        fontSize: 14,
    },
    cardBrandsRow: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 8,
        marginTop: 24,
    },
    brandIconBox: {
        width: 44,
        height: 28,
        borderRadius: 4,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: Colors.light.greybuttonversion,
    },
    brandVisa: { backgroundColor: "#1A1F71" },
    brandMC: { backgroundColor: "#EB001B" },
    brandDiners: { backgroundColor: "#004A97" },
    brandDiscover: { backgroundColor: "#FF6600" },
    brandAmex: { backgroundColor: "#007BC1" },
    brandIconText: {
        color: Colors.light.white,
        fontFamily: fonts.primary.semiBold,
        fontSize: 8,
    },
    // ── Bottom Sheet: Select Payment Method ──
    sheetTitle: {
        color: Colors.light.white,
        fontFamily: fonts.primary.semiBold,
        fontSize: 18,
        marginBottom: 24,
    },
    sheetSectionLabel: {
        color: Colors.light.subtext,
        fontFamily: fonts.primary.medium,
        fontSize: 12,
        marginBottom: 8,
    },
    sheetCardRow: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: Colors.light.calendarBg,
        borderRadius: 8,
        paddingHorizontal: 14,
        paddingVertical: 14,
        marginBottom: 16,
        borderWidth: 1.5,
        borderColor: "transparent",
    },
    sheetCardRowSelected: {
        borderColor: Colors.light.green,
    },
    sheetCardText: {
        color: Colors.light.white,
        fontFamily: fonts.primary.medium,
        fontSize: 14,
        marginLeft: 12,
    },
    newCardIconBox: {
        width: 36,
        height: 28,
        backgroundColor: Colors.light.greybuttonversion,
        borderRadius: 4,
        alignItems: "center",
        justifyContent: "center",
    },
    sheetButtonContainer: {
        marginTop: 16,
    },
    // ── Bottom Sheet 2: Add New Card header ──
    newCardSheetHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 24,
    },
    backCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: Colors.light.greybuttonversion,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    newCardSheetTitle: {
        color: Colors.light.white,
        fontFamily: fonts.primary.semiBold,
        fontSize: 18,
        flex: 1,
        textAlign: "center",
        marginRight: 48, // offset for the back button
    },
});
