import { fonts } from "@/assets/fonts";
import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const createReadMoreStyles = () =>
  StyleSheet.create({
    body: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      alignSelf: "flex-start",
      width: "100%",
    },
    bodyTight: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.3,
      alignSelf: "flex-start",
      width: "100%",
    },
    bodyMediumTight: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.2,
      alignSelf: "flex-start",
      width: "100%",
    },
    bodyZero: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      alignSelf: "flex-start",
      width: "100%",
    },
    tableGuide: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.1,
      alignSelf: "flex-start",
      width: "100%",
    },
    sectionHeading: {
      color: Colors.light.white,
      fontFamily: fonts.primary.semiBold,
      fontWeight: "600",
      fontSize: 16,
      lineHeight: 20,
      letterSpacing: 0,
      alignSelf: "flex-start",
      
      marginBottom: 4,
    },
    paragraphHeading: {
      color: Colors.light.white,
      fontFamily: fonts.primary.semiBold,
      fontWeight: "600",
      fontSize: 14,
      lineHeight: 18,
      letterSpacing: 0,
    },
    prayerHeading: {
      color: Colors.light.white,
      fontFamily: fonts.primary.bold,
      fontWeight: "600",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      alignSelf: "flex-start",
      width: "100%",
      marginBottom: 6,
    },
    quoteItalic: {
      color: Colors.light.white,
      fontFamily: fonts.primary.mediumItalic,
      fontWeight: "500",
      fontStyle: "italic",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.1,
      alignSelf: "flex-start",
      width: "100%",
    },
    quoteSemibold: {
      color: Colors.light.white,
      fontFamily: fonts.primary.semiBold,
      fontWeight: "600",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      alignSelf: "flex-start",
      width: "100%",
    },
    quoteMediumItalic: {
      color: Colors.light.white,
      fontFamily: fonts.primary.mediumItalic,
      fontWeight: "500",
      fontStyle: "italic",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.1,
      alignSelf: "flex-start",
      width: "100%",
    },
    hadithQuoteLead: {
      color: Colors.light.white,
      fontFamily: fonts.primary.mediumItalic,
      fontSize: 14,
      fontWeight: "500",
      fontStyle: "italic",
      lineHeight: 22,
      alignSelf: "flex-start",
      width: "100%",
    },
    hadithQuoteLight: {
      color: Colors.light.white,
      fontFamily: fonts.primary.lightItalic,
      fontSize: 14,
      fontWeight: "400",
      fontStyle: "italic",
      lineHeight: 22,
      alignSelf: "flex-start",
      width: "100%",
      marginBottom: 12,
    },
    wuduBody: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 22,
      alignSelf: "flex-start",
      width: "100%",
    },
    wuduBodySpaced: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 22,
      alignSelf: "flex-start",
      width: "100%",
      marginTop: 16,
    },
    bilalQuote: {
      color: Colors.light.white,
      fontFamily: fonts.primary.medium,
      fontWeight: "500",
      fontStyle: "italic",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.1,
      alignSelf: "flex-start",
      width: "100%",
      marginTop: 12,
    },
    bilalQuoteLight: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontStyle: "italic",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.1,
      alignSelf: "flex-start",
      width: "100%",
    },
    bilalReply: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      alignSelf: "flex-start",
      width: "100%",
      marginTop: 12,
    },
    bilalReplyQuote: {
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontStyle: "italic",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      color: Colors.light.white,
    },
    benefitSection: {
      width: "100%",
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "flex-start",
    },
    benefitHeading: {
      color: Colors.light.white,
      fontSize: 14,
      fontFamily: fonts.primary.semiBold,
      fontWeight: "600",
      lineHeight: 22,
      alignSelf: "flex-start",
      marginBottom: 4,
    },
    benefitDescription: {
      color: Colors.light.white,
      fontSize: 14,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      lineHeight: 22,
      alignSelf: "flex-start",
      width: "100%",
    },
    blockSpacing: {
      marginTop: 12,
    },
    quoteSpacing: {
      marginTop: 8,
    },
    prayerSection: {
      width: "100%",
      marginTop: 16,
      alignSelf: "flex-start",
    },
    prayerSectionFirst: {
      marginTop: 0,
    },
    prayerDescription: {
      marginTop: 0,
    },
    tableContainer: {
      width: "100%",
      borderWidth: 1,
      borderColor: Colors.light.white,
      borderRadius: 1,
      overflow: "hidden",
      marginTop: 12,
    },
    tableHeaderRow: {
      flexDirection: "row",
      //backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderBottomWidth: 1,
      borderColor: Colors.light.white,
    },
    tableHeaderCell: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 4,
      justifyContent: "center",
      alignItems: "center",
    },
    tableHeaderText: {
      color: Colors.light.white,
      fontFamily: fonts.primary.semiBold,
      fontWeight: "600",
      fontSize: 10,
      textAlign: "center",
      lineHeight: 12,
    },
    tableHeaderSubText: {
      color: Colors.light.white,
      fontFamily: fonts.primary.regular,
      fontWeight: "400",
      fontSize: 8,
      textAlign: "center",
      lineHeight: 10,
      marginTop: 2,
    },
    tableRow: {
      flexDirection: "row",
    },
    tableCell: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 4,
      justifyContent: "center",
      alignItems: "center",
    },
    tableCellTextWord: {
      color: Colors.light.white,
      fontFamily: fonts.primary.semiBold,
      fontWeight: "600",
      fontSize: 10,
      textAlign: "center",
      lineHeight: 12,
    },
    tableCellTextCount: {
      color: Colors.light.white,
      fontFamily: fonts.primary.semiBold,
      fontWeight: "600",
      fontSize: 12,
      textAlign: "center",
      lineHeight: 14,
    },
    borderRightWhite: {
      borderRightWidth: 1,
      borderColor: Colors.light.white,
    },
    borderBottomWhite: {
      borderBottomWidth: 1,
      borderColor: Colors.light.white,
    },
  });

export const styles = StyleSheet.create({
  scrollContent: {
    paddingBottom: 24,
  },
});
