import { fonts } from "@/assets/fonts";
import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const manageTeamStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.light.blackBackground,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  banner: {
    width: "100%",
    height: 240,
  },
  bannerGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  editBannerRow: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    zIndex: 1,
    paddingTop: 24,
  },
  editIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.2,
  },
  editBannerText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 13,
    textTransform: "uppercase",
  },
  identityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    marginTop: -36,
    marginBottom: 20,
  },
  logoWrap: {
    position: "relative",
    width: 72,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: Colors.light.darkgrey,
    borderWidth: 2,
    borderColor: Colors.light.blackBackground,
  },
  logoEditBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  logoEditCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.2,
  },
  nameCard: {
    flex: 1,
    backgroundColor: Colors.light.greybuttonBackground,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 64,
    justifyContent: "center",
  },
  nameLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontSize: 10,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  nameInput: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 15,
    padding: 0,
  },
  body: {
    paddingHorizontal: 16,
  },
  sectionLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 12,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  aboutInput: {
    minHeight: 110,
    borderRadius: 10,
    backgroundColor: Colors.light.greybuttonBackground,
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontSize: 13,
    lineHeight: 20,
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: "transparent",
  },
  aboutInputError: {
    borderColor: Colors.light.red,
  },
  charCount: {
    alignSelf: "flex-end",
    marginTop: 6,
    color: Colors.light.subtext,
    fontFamily: fonts.primary.regular,
    fontSize: 11,
  },
  charCountError: {
    color: Colors.light.red,
  },
  chatRow: {
    marginTop: 20,
    marginBottom: 8,
  },
  footerActions: {
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: Colors.light.blackBackground,
  },
  removeMemberButton: {
    borderColor: "#8E98A8",
  },
  removeMemberButtonText: {
    color: "#8E98A8",
  },
  saveYesButton: {
    borderWidth: 1.5,
    borderColor: Colors.light.green,
    backgroundColor: "transparent",
    borderRadius: 6,
    width: "60%",
    paddingVertical: 4,
  },
  saveYesButtonText: {
    color: Colors.light.green,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 14,
  },
  saveCancelText: {
    color: Colors.light.white,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: Colors.light.greybuttonBackground,
    borderRadius: 22,
    minHeight: 44,
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontSize: 14,
    paddingVertical: 8,
  },
  crownButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#D4A017",
    alignItems: "center",
    justifyContent: "center",
  },
  crownButtonSelected: {
    backgroundColor: "rgba(212, 160, 23, 0.2)",
  },
  confirmCard: {
    backgroundColor: Colors.light.calendarBg,
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 18,
    marginTop: 8,
  },
  confirmTitle: {
    color: Colors.light.white,
    fontFamily: fonts.primary.bold,
    fontSize: 15,
    textAlign: "center",
    textTransform: "uppercase",
    marginBottom: 10,
  },
  confirmMessage: {
    color: Colors.light.dullWhite,
    fontFamily: fonts.primary.regular,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 18,
  },
  confirmTextButton: {
    alignItems: "center",
    paddingVertical: 10,
  },
  confirmTextButtonLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontSize: 13,
  },
});
