import { fonts } from "@/assets/fonts";
import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const behaviorDetailStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.light.blackBackground,
  },
  scrollContainer: {
    flex: 1,
  },
  screenHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  scrollBody: {
    paddingHorizontal: 16,
    backgroundColor: Colors.light.blackBackground,
  },
  heroSticky: {
    width: "100%",
    backgroundColor: Colors.light.blackBackground,
  },
  heroImage: {
    width: "100%",
  },
  heroTextContainer: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  heroTitle: {
    color: Colors.light.white,
    fontSize: 18,
    fontWeight: "500",
    fontFamily: fonts.primary.semiBold,
    lineHeight: 22,
  },
  heroRingContainer: {
    position: "absolute",
    top: "28%",
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  heroRingCount: {
    color: Colors.light.white,
    fontSize: 34,
    fontWeight: "400",
    fontFamily: fonts.primary.regular,
    lineHeight: 38,
  },
  summaryText: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    lineHeight: 21,
    opacity: 0.9,
    marginTop: 20,
  },
  weekDaysRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 4,
    marginTop: 18,
  },
  weekDayItem: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  dayCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: Colors.light.calendarBg,
  },
  dayCircleCompleted: {
    backgroundColor: Colors.light.green,
    borderColor: Colors.light.green,
  },
  dayCirclePartial: {
    backgroundColor: Colors.light.calendarBg,
    borderColor: Colors.light.calendarBg,
  },
  dayCircleMissed: {
    backgroundColor: Colors.light.calendarBg,
    borderColor: Colors.light.calendarBg,
  },
  dayCircleEmpty: {
    backgroundColor: "transparent",
  },
  weekDayLabel: {
    fontSize: 10,
    fontWeight: "500",
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
  },
  weekDayDate: {
    fontSize: 10,
    fontWeight: "400",
    color: Colors.light.grey,
    fontFamily: fonts.primary.regular,
  },
  chartSection: {
    marginTop: 18,
  },
  chartPlotRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  chartYAxis: {
    width: 18,
    justifyContent: "space-between",
    paddingBottom: 2,
  },
  chartYAxisLabel: {
    fontSize: 10,
    fontWeight: "400",
    color: Colors.light.grey,
    fontFamily: fonts.primary.regular,
    textAlign: "right",
  },
  chartBarsArea: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(160, 160, 160, 0.25)",
  },
  chartBarColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    minWidth: 0,
  },
  chartBarTrack: {
    width: "72%",
    maxWidth: 34,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  chartBarFill: {
    width: "100%",
    borderRadius: 2,
    backgroundColor: Colors.light.green,
  },
  chartXAxisRow: {
    flexDirection: "row",
    marginTop: 8,
    gap: 8,
  },
  chartXAxisSpacer: {
    width: 18,
  },
  chartXAxisItem: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
  },
  chartXAxisLabel: {
    fontSize: 10,
    fontWeight: "400",
    color: Colors.light.grey,
    fontFamily: fonts.primary.regular,
    textAlign: "center",
    lineHeight: 13,
  },
  streakCard: {
    backgroundColor: Colors.light.darkgrey,
    borderRadius: 8,
    paddingVertical: 18,
    paddingHorizontal: 16,
    marginTop: 16,
    flexDirection: "row",
    gap: 12,
  },
  streakItem: {
    flex: 1,
    alignItems: "center",
    gap: 8,
  },
  streakRingWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  streakCount: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.light.white,
    fontFamily: fonts.primary.bold,
  },
  streakLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.light.subtext,
    fontFamily: fonts.primary.semiBold,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    textAlign: "center",
  },
  streakDate: {
    fontSize: 11,
    fontWeight: "500",
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    textAlign: "center",
  },
  sectionCard: {
    backgroundColor: Colors.light.darkgrey,
    borderRadius: 8,
    padding: 16,
    marginTop: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    lineHeight: 21,
    marginBottom: 10,
  },
  sectionBody: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    lineHeight: 21,
    opacity: 0.9,
  },
  quoteBlock: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 14,
  },
  quoteTextWrap: {
    flex: 1,
    gap: 4,
  },
  quoteText: {
    fontSize: 13,
    fontWeight: "400",
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    lineHeight: 20,
    fontStyle: "italic",
    opacity: 0.9,
  },
  quoteSource: {
    fontSize: 12,
    fontWeight: "500",
    color: Colors.light.subtext,
    fontFamily: fonts.primary.medium,
    lineHeight: 18,
  },
  recommendationList: {
    marginTop: 12,
    gap: 12,
  },
  recommendationRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  recommendationBullet: {
    color: Colors.light.white,
    fontSize: 10,
    lineHeight: 20,
    marginTop: 1,
  },
  recommendationText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "400",
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    lineHeight: 21,
    opacity: 0.9,
  },
  closingText: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    lineHeight: 21,
    opacity: 0.9,
    marginTop: 14,
  },
});
