import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/constants/theme";
import { fonts } from "@/assets/fonts";

const WINDOW = Dimensions.get("window");
const OVERLAY_COVER_HEIGHT = WINDOW.height * 4;
export const FLOW_CARD_HEIGHT = WINDOW.height * 0.19;

export const styles = StyleSheet.create({
  backdrop: {
    backgroundColor: Colors.light.overlayBlackColor,
    position: "absolute",
    zIndex: 90,
    elevation: 8,
    top: -WINDOW.height,
    left: -WINDOW.width,
    width: WINDOW.width * 3,
    height: OVERLAY_COVER_HEIGHT,
  },
  section: {
    width: "100%",
    alignSelf: "stretch",
    paddingHorizontal: 0,
    marginTop: 8,
    overflow: "visible",
    marginBottom: 10,
  },
  activeSection: {
    zIndex: 100,
    position: "relative",
    overflow: "visible",
  },
  /**
   * Shared card frame for collapsed + active logging cards.
   * Other goal-card components also reuse this anchor.
   */
  cardAnchor: {
    width: "66%",
    alignSelf: "stretch",
    height: FLOW_CARD_HEIGHT,
    position: "relative",
    zIndex: 101,
    elevation: 12,
    overflow: "visible",
    paddingLeft: 16,
  },
  flowCardLayer: {
    position: "relative",
    zIndex: 101,
    elevation: 12,
    width: "100%",
    height: FLOW_CARD_HEIGHT,
  },
  flowCardLayerDropdownOpen: {
    zIndex: 200,
    elevation: 10,
    overflow: "visible",
  },
  cancelButton: {
    position: "absolute",
    right: "5%",
    top: "6%",
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.light.dullWhiteOpacity,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 110,
    elevation: 16,
  },
  sectionTitle: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 20,
    marginBottom: 12,
    marginLeft: 4,
    paddingHorizontal: 16,
  },
  summaryCard: {
    backgroundColor: Colors.light.green,
    borderRadius: 8,
    padding: 14,
    height: FLOW_CARD_HEIGHT,
    position: "relative",
    width: "100%",
  },
  badge: {
    alignSelf: "flex-start",
    marginLeft: 56,
    backgroundColor: Colors.light.lightpurple,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 5,
    marginBottom: 10,
  },
  badgeText: {
    color: Colors.light.darkblue,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 11,
    lineHeight: 14,
  },
  summaryBody: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 48,
  },
  summaryIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.light.darkgrey,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  summaryTextBlock: {
    flex: 1,
  },
  summaryTitle: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 4,
  },
  summarySubtext: {
    fontSize: 13,
    lineHeight: 18,
  },
  summarySubtextRegular: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 18,
    opacity: 0.95,
  },
  summarySubtextBold: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 13,
    lineHeight: 18,
  },
  addButton: {
    position: "absolute",
    right: 16,
    bottom: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
  },
  flowCard: {
    backgroundColor: Colors.light.mildGreen,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
    width: "100%",
    alignSelf: "stretch",
    height: FLOW_CARD_HEIGHT,
    overflow: "hidden",
  },
  inPlaceFlowCard: {
    width: "100%",
    marginLeft: 0,
    height: FLOW_CARD_HEIGHT,
    overflow: "hidden",
  },
  flowCardDropdownOpen: {
    overflow: "visible",
    zIndex: 200,
    elevation: 10,
  },
  flowContentAyahRange: {
    justifyContent: "flex-start",
    paddingTop: 0,
    paddingBottom: 0,
    marginBottom: 0,
    overflow: "visible",
  },
  flowHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  flowIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.light.selectcategory,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  flowHeaderText: {
    flex: 1,
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 14,
    lineHeight: 18,
  },
  flowContent: {
    flex: 1,
    justifyContent: "center",
    minHeight: 40,
    marginBottom: 4,
    overflow: "visible",
  },
  flowContentDropdownOpen: {
    overflow: "visible",
    zIndex: 30,
  },
  flowFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  navGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
    flex: 1,
    justifyContent: "center",
    transform: [{ translateX: 14 }],
  },
  navButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.light.dullWhiteOpacity,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ translateY: 0 }],
  },
  navButtonDisabled: {
    opacity: 0.6,
  },
  confirmButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: Colors.light.white + "99",
    backgroundColor: Colors.light.white + "29",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ translateY: -6 }],
  },
  confirmButtonActive: {
    borderColor: Colors.light.white,
    backgroundColor: Colors.light.white + "10",
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  dateMainText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
  },
  prayerGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    width: "100%",
    paddingHorizontal: 0,
  },
  prayerColumn: {
    flex: 1,
    alignItems: "center",
    minWidth: 0,
    position: "relative",
  },
  prayerLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 8,
    lineHeight: 11,
    marginBottom: 6,
    textAlign: "center",
  },
  prayerIconBox: {
    width: "90%",
    paddingVertical: 3,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  prayerIconBoxSelected: {
    backgroundColor: Colors.light.white,
  },
  prayerIconBoxIdle: {
    backgroundColor: Colors.light.idlePrayerBox,
  },
  prayerCheckBadge: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    overflow: "hidden",
  },
  timingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    width: "100%",
  },
  timingOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  radioOuter: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterSelected: {},
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.light.white,
  },
  timingLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
  },
  timePickerContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  timePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    zIndex: 100,
  },
  timeInput: {
    borderWidth: 1.5,
    borderColor: Colors.light.white + "66",
    borderRadius: 6,
    width: 34,
    height: 26,
    padding: 0,
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontSize: 14,
    textAlign: "center",
  },
  timeSeparator: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontSize: 16,
    marginHorizontal: 1,
  },
  dropdownWrapper: {
    position: "relative",
  },
  flowDropdownWrapper: {
    position: "relative",
    width: "100%",
  },
  flowDropdownSelector: {
    borderWidth: 1.5,
    borderColor: Colors.light.dullWhiteOpacity,
    borderRadius: 6,
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 8,
  },
  flowDropdownValue: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 13,
    flex: 1,
  },
  flowDropdownPlaceholder: {
    color: Colors.light.subtext,
  },
  flowDropdownMenu: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: Colors.light.blackBackground,
    borderRadius: 6,
    marginTop: 4,
    paddingVertical: 8,
    paddingHorizontal: 6,
    zIndex: 999,
    maxHeight: 200,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  flowDropdownOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 4,
    width: "100%",
  },
  periodSelector: {
    borderWidth: 1.5,
    borderColor: Colors.light.white + "66",
    borderRadius: 6,
    height: 26,
    width: 47,
    paddingHorizontal: 6,
    paddingVertical: 0,
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  periodText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontSize: 14,
  },
  periodDropdown: {
    position: "absolute",
    top: 26,
    right: -1,
    backgroundColor: Colors.light.blackBackground,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 6,
    minWidth: 47,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 999,
  },
  dropdownOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingVertical: 0,
  },
  dropdownRadioOuter: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
  },
  dropdownRadioInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.light.green,
  },
  dropdownOptionText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontSize: 12,
    lineHeight: 17,
    flex: 1,
    flexShrink: 1,
  },
  timeUnitLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontSize: 14,
    marginLeft: -1,
    marginRight: 9,
    fontWeight: "400",
    opacity: 0.8,
  },
  recitationCounterRow: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.light.white,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 12,
  },
  recitationCounterControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    // gap: 16,
  },
  recitationCounterValueColumn: {
    gap: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  recitationCounterValue: {
    borderWidth: 1.5,
    borderColor: Colors.light.dullWhiteOpacity,
    borderRadius: 8,
    width: 48,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  recitationCounterValueText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
  },
  recitationMaxLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontWeight: "400",
    fontSize: 11,
    lineHeight: 14,
    opacity: 0.95,
    textAlign: "center",
  },
  recitationProgressLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 16,
    opacity: 0.9,
    textAlign: "center",
    marginBottom: 8,
  },
});
