import { StyleSheet } from "react-native";
import { Colors } from "@/constants/theme";
import { fonts } from "@/assets/fonts";

export const styles = StyleSheet.create({
  backdrop: {
    position: "absolute",
    top: -3000,
    bottom: -3000,
    left: -1000,
    right: -1000,
    backgroundColor: Colors.light.overlayBlackColor,
    zIndex: 90,
  },
  section: {
    width: "100%",
    paddingHorizontal: 16,
    marginTop: 8,
    overflow: "visible",
    flexGrow: 1,
  },
  activeSection: {
    zIndex: 100,
    position: "relative",
    overflow: "visible",
  },
  cardAnchor: {
    width: "80%",
    alignSelf: "flex-start",
    minHeight: 155,
    position: "relative",
    zIndex: 101,
    overflow: "visible",
  },
  flowCardLayer: {
    position: "relative",
    zIndex: 101,
  },
  cancelButton: {
    position: "absolute",
    right: -8,
    top: -72,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.light.dullWhiteOpacity,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 110,
  },
  sectionTitle: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 20,
    marginBottom: 12,
    marginLeft: 4,
  },
  summaryCard: {
    backgroundColor: Colors.light.green,
    borderRadius: 12,
    padding: 14,
    minHeight: 155,
    position: "relative",
    width: "100%",
  },
  badge: {
    alignSelf: "flex-start",
    marginLeft: 56,
    backgroundColor: Colors.light.lightpurple,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 5,
    marginBottom: 10,
  },
  badgeText: {
    color: Colors.light.darkblue,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 11,
    lineHeight: 14,
  },
  summaryBody: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 48,
  },
  summaryIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.light.darkgrey,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  summaryTextBlock: {
    flex: 1,
  },
  summaryTitle: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 4,
  },
  summarySubtext: {
    fontSize: 13,
    lineHeight: 18,
  },
  summarySubtextRegular: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 18,
    opacity: 0.95,
  },
  summarySubtextBold: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 13,
    lineHeight: 18,
  },
  addButton: {
    position: "absolute",
    right: 16,
    bottom: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
  },
  flowCard: {
    backgroundColor: Colors.light.green,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    height: 155,
    width: "80%",
    alignSelf: "flex-start",
    marginLeft: -8,
  },
  inPlaceFlowCard: {
    width: "100%",
    marginLeft: 0,
    alignSelf: "stretch",
  },
  flowHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  flowIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.light.darkgrey,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  flowHeaderText: {
    flex: 1,
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 14,
    lineHeight: 20,
  },
  flowContent: {
    flex: 1,
    justifyContent: "center",
    minHeight: 40,
    marginBottom: 12,
  },
  flowFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  navGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 32,
    flex: 1,
    justifyContent: "center",
    transform: [{ translateX: 14 }],
  },
  navButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.light.dullWhiteOpacity,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ translateY: -3 }],
  },
  navButtonDisabled: {
    opacity: 0.5,
  },
  confirmButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: Colors.light.white + "99",
    backgroundColor: Colors.light.white + "26",
    alignItems: "center",
    justifyContent: "center",
    //transform: [{ translateY: -0 }],
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  dateMainText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
  },
  prayerGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 2,
  },
  prayerColumn: {
    alignItems: "center",
    width: 44,
    position: "relative",
  },
  prayerLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
    fontSize: 8,
    lineHeight: 11,
    marginBottom: 6,
    textAlign: "center",
  },
  prayerIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  prayerIconBoxSelected: {
    backgroundColor: Colors.light.white,
  },
  prayerIconBoxIdle: {
    backgroundColor: Colors.light.dullWhiteOpacity,
  },
  prayerCheckBadge: {
    position: "absolute",
    bottom: -5,
    width: 13,
    height: 13,
    borderRadius: 6.5,
    backgroundColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
  },
  timingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 32,
  },
  timingOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterSelected: {},
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 6,
    backgroundColor: Colors.light.white,
  },
  timingLabel: {
    color: Colors.light.white,
    fontFamily: fonts.primary.medium,
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
  },
  timePickerContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  timePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    zIndex: 100,
  },
  timeInput: {
    borderWidth: 1.5,
    borderColor: Colors.light.dullWhiteOpacity,
    borderRadius: 8,
    width: 48,
    height: 40,
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontSize: 16,
    textAlign: "center",
  },
  timeSeparator: {
    color: Colors.light.white,
    fontFamily: fonts.primary.semiBold,
    fontSize: 20,
    marginHorizontal: 2,
  },
  dropdownWrapper: {
    position: "relative",
  },
  periodSelector: {
    borderWidth: 1.5,
    borderColor: Colors.light.dullWhiteOpacity,
    borderRadius: 8,
    height: 40,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  periodText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontSize: 16,
  },
  periodDropdown: {
    position: "absolute",
    top: 44,
    right: 0,
    backgroundColor: Colors.light.blackBackground,
    borderRadius: 8,
    padding: 8,
    minWidth: 70,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 999,
  },
  dropdownOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 4,
  },
  dropdownRadioOuter: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: Colors.light.white,
    alignItems: "center",
    justifyContent: "center",
  },
  dropdownRadioInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.light.green,
  },
  dropdownOptionText: {
    color: Colors.light.white,
    fontFamily: fonts.primary.regular,
    fontSize: 14,
  },
  timeUnitLabel: {
    color: Colors.light.subtext,
    fontFamily: fonts.primary.regular,
    fontSize: 16,
    marginLeft: 4,
    marginRight: 12,
  },
});
