import { fonts } from "@/assets/fonts";
import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const planStyles = StyleSheet.create({
  tabBarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 36,
  },
  tabBarScrollContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 36,
    flexGrow: 0,
    paddingRight: 4,
  },
  tabButton: {
    padding: 8,
    borderBottomWidth: 0,
    borderBottomColor: "transparent",
  },
  tabButtonScrollable: {
    flexShrink: 0,
  },
  tabButtonActive: {
    borderBottomWidth: 2,
    borderBottomColor: Colors.light.green,
  },
  tabLabel: {
    fontWeight: "500",
    fontSize: 18,
    fontFamily: fonts.primary.medium,
    color: Colors.light.grey,
  },
  tabLabelActive: {
    color: Colors.light.white,
  },
  journalTabScroll: {
    flexGrow: 0,
    flexShrink: 0,
  },
  goalTabContent: {
    paddingBottom: 24,
  },
  journalTabContent: {
    paddingBottom: 24,
  },
  goalsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  goalsTitle: {
    fontWeight: "500",
    fontSize: 18,
    fontFamily: fonts.primary.medium,
    color: Colors.light.white,
  },
  goalPlanButton: {
    width: "60%",
    borderWidth: 1,
    borderColor: Colors.light.green,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 5,
    borderRadius: 6,
  },
  goalProgressCard: {
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: Colors.light.darkgrey,
  },
  goalProgressRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  moonProgressWrap: {
    height: 70,
    width: 70,
  },
  goalProgressText: {
    flex: 1,
    flexShrink: 1,
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.white,
  },
  viewProposedPlanRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    alignSelf: "center",
  },
  viewProposedPlanText: {
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.green,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionHeaderTitle: {
    color: Colors.light.white,
    fontWeight: "500",
    fontSize: 16,
    fontFamily: fonts.primary.medium,
    textTransform: "uppercase",
  },
  sectionHeaderActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  proposedPlanCard: {
    width: "100%",
    borderRadius: 8,
    overflow: "hidden",
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  proposedPlanCardImage: {
    borderRadius: 8,
  },
  proposedPlanOverlay: {
    ...StyleSheet.absoluteFill,
    borderRadius: 8,
  },
  proposedPlanContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  proposedPlanTextBlock: {
    flex: 1,
    flexShrink: 1,
  },
  proposedPlanDescription: {
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.white,
    lineHeight: 20,
  },
  proposedPlanDescriptionDigit: {
    fontSize: 14,
    fontFamily: fonts.primary.bold,
    fontWeight: "700",
    color: Colors.light.white,
  },
  proposedPlanAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
  },
  proposedPlanActionText: {
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.green,
  },
  recordScroll: {
    flexGrow: 0,
    flexShrink: 0,
  },
  recordScrollContent: {
    flexGrow: 0,
    alignItems: "flex-start",
    gap: 10,
    paddingRight: 4,
  },
  recordCard: {
    backgroundColor: Colors.light.greybuttonBackground,
    padding: 12,
    borderRadius: 8,
  },
  recordCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 40,
  },
  recordCardText: {
    flexShrink: 1,
  },
  recordCardDuration: {
    color: Colors.light.grey,
    fontWeight: "600",
    fontSize: 10,
    fontFamily: fonts.primary.medium,
    textTransform: "uppercase",
    lineHeight: 12,
  },
  recordCardValue: {
    fontWeight: "600",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    lineHeight: 18,
    color: Colors.light.white,
  },
  journalBanner: {
    backgroundColor: Colors.light.darkgrey,
    padding: 20,
    borderRadius: 8,
  },
  journalBannerDismiss: {
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.white,
    position: "absolute",
    top: 10,
    right: 20,
  },
  journalBannerText: {
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.white,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
  },
  achievementBlock: {
    flex: 3,
    alignItems: "flex-start",
    gap: 4,
  },
  consistencyCaptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  consistencyInfoBadge: {
    backgroundColor: Colors.light.darkgrey,
    height: 12,
    width: 12,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  achievementPercent: {
    color: Colors.light.white,
    fontSize: 40,
    fontFamily: fonts.primary.regular,
    fontWeight: "400",
    lineHeight: 44,
  },
  achievementPercentSymbol: {
    fontSize: 22,
  },
  achievementCaption: {
    color: Colors.light.subtext,
    fontSize: 13,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
  },
  deltaBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.light.lightgreen,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 2,
    alignSelf: "flex-start",
    maxWidth: "100%",
  },
  deltaBadgeNegative: {
    backgroundColor: Colors.light.dullWhiteOpacity,
  },
  deltaText: {
    color: Colors.light.green,
    fontSize: 11,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
  },
  deltaTextNegative: {
    color: Colors.light.subtext,
  },
  periodNavRow: {
    flex: 6,
    minWidth: 0,
    alignItems: "stretch",
    gap: 10,
  },
  periodToggle: {
    flexDirection: "row",
    alignItems: "center",
    padding: 3,
    backgroundColor: Colors.light.blackBackground,
    borderRadius: 6,
    width: "100%",
  },
  periodButton: {
    flex: 1,
    borderRadius: 5,
    paddingHorizontal: 2,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
  },
  periodButtonActive: {
    backgroundColor: Colors.light.greybuttonBackground,
  },
  periodButtonInactive: {
    backgroundColor: Colors.light.blackBackground,
  },
  periodButtonText: {
    color: Colors.light.grey,
    fontSize: 11,
    fontFamily: fonts.primary.medium,
    fontWeight: "500",
    textAlign: "center",
  },
  periodButtonTextActive: {
    color: Colors.light.green,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "600",
  },
  dateNavRow: {
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 2,
    minHeight: 28,
    alignSelf: "center",
  },
  navBtn: {
    width: 24,
    alignItems: "center",
    justifyContent: "center",
    padding: 2,
    flexShrink: 0,
  },
  dateRange: {
    color: Colors.light.white,
    fontSize: 16,
    fontFamily: fonts.primary.semiBold,
    fontWeight: "500",
    textAlign: "center",
    flex: 1,
    minWidth: 0,
  },
  journalHabitCard: {
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: Colors.light.darkgrey,
    marginBottom: 10,
  },
  journalHabitRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  journalHabitIconWrap: {
    height: 40,
    width: 40,
    backgroundColor: Colors.light.selectcategory,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  journalHabitName: {
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.white,
    flex: 1,
  },
  journalHabitPercentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  journalHabitPercentText: {
    fontWeight: "500",
    fontSize: 14,
    fontFamily: fonts.primary.medium,
    color: Colors.light.white,
  },
  journalCustomizeCard: {
    borderRadius: 8,
    backgroundColor: Colors.light.darkgrey,
    padding: 15,
  },
  journalCustomizeImage: {
    width: "100%",
    height: 400,
    borderRadius: 8,
  },
  journalCustomizeTitle: {
    fontWeight: "600",
    fontSize: 18,
    fontFamily: fonts.primary.semiBold,
    color: Colors.light.white,
  },
  journalCustomizeHabitRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
  },
  journalCustomizeHabitTextBlock: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  journalCustomizeHabitTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.light.white,
  },
  journalCustomizeHabitDescription: {
    fontSize: 14,
    color: Colors.light.white,
    fontWeight: "400",
    fontFamily: fonts.primary.regular,
    lineHeight: 20,
  },
  journalCustomizeHabitIconWrap: {
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  journalCustomizeHabitCheckWrap: {
    width: 28,
    height: 28,
    backgroundColor: Colors.light.green,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  journalCustomizeSheetTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.light.white,
    textAlign: "center",
  },
  journalCustomizeSheetDescription: {
    fontSize: 14,
    color: Colors.light.white,
    fontWeight: "500",
    fontFamily: fonts.primary.mediumItalic,
    opacity: 0.8,
    lineHeight: 20,
  },
  journalCustomizeSheetListContent: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  journalCustomizeSheetFooter: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: Colors.light.darkgrey,
  },
});
